[export]
enabled = true
limit = 1000
folder = "exports"

[local_model]
enabled = true
url = "http://localhost:8080"
batch_size = 16
n_predict = 20
temp = 0.5

[benchmark]
folder = "exports"
output = "benchmark"

[logging]
level = "INFO"
format = "%(asctime)s [%(levelname)s] [%(name)s] %(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"
file = "tawos.log"
